namespace Api.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Icons 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public Icons()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resources.Icons", typeof(Icons).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-content-copy.
	/// </summary>
	public static string Copy => ResourceManager.GetString("Copy", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-plus.
	/// </summary>
	public static string Create => ResourceManager.GetString("Create", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-delete.
	/// </summary>
	public static string Delete => ResourceManager.GetString("Delete", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-check-all.
	/// </summary>
	public static string Done => ResourceManager.GetString("Done", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-pencil.
	/// </summary>
	public static string Edit => ResourceManager.GetString("Edit", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to En.
	/// </summary>
	public static string English => ResourceManager.GetString("English", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-login.
	/// </summary>
	public static string Login => ResourceManager.GetString("Login", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-logout.
	/// </summary>
	public static string Logout => ResourceManager.GetString("Logout", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-thumb-down-outline.
	/// </summary>
	public static string No => ResourceManager.GetString("No", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to فا.
	/// </summary>
	public static string Persian => ResourceManager.GetString("Persian", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-arrow-left.
	/// </summary>
	public static string Return => ResourceManager.GetString("Return", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-content-save.
	/// </summary>
	public static string Save => ResourceManager.GetString("Save", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-check.
	/// </summary>
	public static string SetDone => ResourceManager.GetString("SetDone", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi-24px.
	/// </summary>
	public static string Size24 => ResourceManager.GetString("Size24", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi-36px.
	/// </summary>
	public static string Size36 => ResourceManager.GetString("Size36", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to mdi mdi-thumb-up-outline.
	/// </summary>
	public static string Yes => ResourceManager.GetString("Yes", Culture);
}
