namespace Api.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Messages 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public Messages()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resources.Messages", typeof(Messages).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to حساب کابری ندارید؟.
	/// </summary>
	public static string DontHaveAcc => ResourceManager.GetString("DontHaveAcc", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to این نام کاربری قبلا استفاده شده است.
	/// </summary>
	public static string DuplicateUsername => ResourceManager.GetString("DuplicateUsername", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to قبلا ثبت نام کرده اید؟.
	/// </summary>
	public static string HaveAcc => ResourceManager.GetString("HaveAcc", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to حساب کاربر با موفقیت خارج شد.
	/// </summary>
	public static string Logout => ResourceManager.GetString("Logout", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to مقدار {0} نمیتواند بیشتر از {1} کاراکتر باشد..
	/// </summary>
	public static string MaxLength => ResourceManager.GetString("MaxLength", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to مقدار appsetting یافت نشد.
	/// </summary>
	public static string NullAppSetting => ResourceManager.GetString("NullAppSetting", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to مقادیر زمز عبور و تایید رمز عبور باید یکسان باشند..
	/// </summary>
	public static string PassNotConfirmed => ResourceManager.GetString("PassNotConfirmed", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to مقدار {0} نمیتواند خالی باشد..
	/// </summary>
	public static string RequierdField => ResourceManager.GetString("RequierdField", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to {0} مورد نظر یافت نشد.
	/// </summary>
	public static string SomeNotFound => ResourceManager.GetString("SomeNotFound", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to مشکلی پیش آمده است لطفا صبور باشید ....
	/// </summary>
	public static string SomethingWrong => ResourceManager.GetString("SomethingWrong", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to عملیات {0} با موفقیت انجام شد..
	/// </summary>
	public static string SuccessfulAction => ResourceManager.GetString("SuccessfulAction", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to عملیات {0} با موفقیت انجام نشد..
	/// </summary>
	public static string UnSuccessfulAction => ResourceManager.GetString("UnSuccessfulAction", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
	/// </summary>
	public static string WrongUsernamePassword => ResourceManager.GetString("WrongUsernamePassword", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to در بازکردن صفحه مورد نظر مشکلی پیش آمده است.
	/// </summary>
	public static string OpeningPageUnsuccessful => ResourceManager.GetString("OpeningPageUnsuccessful", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to خواهشا در زمانی دیگر تلاش کنید و یا با پشتیبانی تماس بگیرید.
	/// </summary>
	public static string PleaseTryAgainOrCall => ResourceManager.GetString("PleaseTryAgainOrCall", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to سرور مورد نظر غیرفعال می باشد، لطفا در زمان دیگری اقدام فرمایید..
	/// </summary>
	public static string ServerDown => ResourceManager.GetString("ServerDown", Culture);
}
