namespace Api.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Titles 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public Titles()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resources.Titles", typeof(Titles).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to لغو.
	/// </summary>
	public static string Cancel => ResourceManager.GetString("Cancel", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to تایید رمز عبور.
	/// </summary>
	public static string ConfirmPassword => ResourceManager.GetString("ConfirmPassword", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to نام خانوادگی.
	/// </summary>
	public static string LastName => ResourceManager.GetString("LastName", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to شناسه.
	/// </summary>
	public static string Id => ResourceManager.GetString("Id", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to ورود.
	/// </summary>
	public static string Login => ResourceManager.GetString("Login", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to خروج.
	/// </summary>
	public static string Logout => ResourceManager.GetString("Logout", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to نام.
	/// </summary>
	public static string Name => ResourceManager.GetString("Name", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to خیر.
	/// </summary>
	public static string No => ResourceManager.GetString("No", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to رمز عبور.
	/// </summary>
	public static string Password => ResourceManager.GetString("Password", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to ثبت نام.
	/// </summary>
	public static string Register => ResourceManager.GetString("Register", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to حالت اولیه.
	/// </summary>
	public static string Reset => ResourceManager.GetString("Reset", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to ذخیره.
	/// </summary>
	public static string Save => ResourceManager.GetString("Save", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to تسک.
	/// </summary>
	public static string Task => ResourceManager.GetString("Task", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to نام کاربری.
	/// </summary>
	public static string Username => ResourceManager.GetString("Username", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to بله.
	/// </summary>
	public static string Yes => ResourceManager.GetString("Yes", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to تمام.
	/// </summary>
	public static string Done => ResourceManager.GetString("Done", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to حذف.
	/// </summary>
	public static string Delete => ResourceManager.GetString("Delete", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to ویرایش.
	/// </summary>
	public static string Edit => ResourceManager.GetString("Edit", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to انجام شد.
	/// </summary>
	public static string SetDone => ResourceManager.GetString("SetDone", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to ایجاد.
	/// </summary>
	public static string Create => ResourceManager.GetString("Create", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to English.
	/// </summary>
	public static string English => ResourceManager.GetString("English", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to فارسی.
	/// </summary>
	public static string Persian => ResourceManager.GetString("Persian", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to عنوان.
	/// </summary>
	public static string Title => ResourceManager.GetString("Title", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to شرح.
	/// </summary>
	public static string Description => ResourceManager.GetString("Description", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to بازگشت.
	/// </summary>
	public static string Return => ResourceManager.GetString("Return", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to کپی.
	/// </summary>
	public static string Copy => ResourceManager.GetString("Copy", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to فراخوانی.
	/// </summary>
	public static string Call => ResourceManager.GetString("Call", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to ثبت.
	/// </summary>
	public static string Submit => ResourceManager.GetString("Submit", Culture);
}
